### ISSUE TITLE
raise JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by ninamculver** [terryyin/translate-python#54]
Attempted to mimic the example and ran into the following error: 

```
from translate import Translator
translator= Translator(to_lang="zh")
translation = translator.translate("This is a pen.")
```

[Traceback (most recent call last):

  File "<ipython-input-36-cc6af7841e10>", line 3, in <module>
    translation = translator.translate("This is a pen.")

  File "C:\ProgramData\Anaconda3\lib\site-packages\translate\translate.py", line 42, in translate
    return ' '.join(self.provider.get_translation(text_wraped) for text_wraped in text_list)

  File "C:\ProgramData\Anaconda3\lib\site-packages\translate\translate.py", line 42, in <genexpr>
    return ' '.join(self.provider.get_translation(text_wraped) for text_wraped in text_list)

  File "C:\ProgramData\Anaconda3\lib\site-packages\translate\providers\mymemory_translated.py", line 42, in get_translation
    data = self._make_request(text)

  File "C:\ProgramData\Anaconda3\lib\site-packages\translate\providers\mymemory_translated.py", line 39, in _make_request
    return response.json()

  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)

  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value](url)

**Comment by timurhamzin** [comment]
I'm having the same issue.

**Comment by aquaknight** [comment]
Hello, 

Was anyone able to address it yet? I have the same problem. 

Funny thing, the exact same code runs just fine when I use my home laptop. I have tried uninstalling and reinstalling translate, but to no avail.

![image](https://user-images.githubusercontent.com/29898531/75219480-e413db80-57c2-11ea-9498-c728253d127a.png)

**Comment by ninamculver** [comment]
I realized I was getting this error when the API had reached is maximum. 

I think it’s an error of you’ve attempted it too many times. I ended up switching the code to use a different package.

Thanks!

**Comment by cabhijith** [comment]
@ninamculver Which package? Does that work?

**Comment by rish-hyun** [comment]
@ninamculver Yeah Buddy! Which package are you talking about?

**Comment by Reklexx** [comment]
is this resloved?
