### ISSUE TITLE
Unable to install on mac high sierra

### ISSUE THREAD

**Issue by etherealSunshine** [terryyin/translate-python#70]
When i run pip install, this is what it returns, tried sudo as well,

 Collecting translate
  Downloading https://files.pythonhosted.org/packages/85/b2/2ea329a07bbc0c7227eef84ca89ffd6895e7ec237d6c0b26574d56103e53/translate-3.5.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): lxml in /opt/anaconda3/lib/python3.8/site-packages (from translate)
Requirement already satisfied (use --upgrade to upgrade): requests in /opt/anaconda3/lib/python3.8/site-packages (from translate)
Collecting tox (from translate)
  Downloading https://files.pythonhosted.org/packages/d8/63/2fa635ac1b8a22e960654b07c270dfb53eb873aba261006536de40327b18/tox-3.23.1-py2.py3-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 2.8MB/s 
Exception:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2851, in _dep_map
    return self.__dep_map
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2685, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/req/req_set.py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/req/req_set.py", line 647, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2810, in extras
    return [dep for dep in self._dep_map if dep]
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2853, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2886, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2883, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'platform_system' is not defined

**Comment by terryyin** [comment]
oh, the pip package is probably old. I need to publish a new one.
